

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_manager?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: XIAOSUDA




server:
  port: 8080

mybatis:
  mapper-locations: "classpath:mybatis/*.xml"