

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_manager
    driver-class-name: com.mysql.jdbc.Driver
    username: ROOT
    password: 123456




server:
  port: 8080

mybatis:
  mapper-locations: "classpath:mybatis/*.xml"